services:
  chromadb:
    image: chromadb/chroma:0.5.20
    volumes:
      - chromadata:/chroma/chroma
    ports:
      - "8001:8000"

  searxng:
    image: searxng/searxng:latest
    volumes:
      - ./searxng:/etc/searxng
    ports:
      - "8080:8080"

networks:
  default:

volumes:
  chromadata:
